name: Pull Request another repository

on: push

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate test folder
      run: |
        mkdir test
        echo "test tile content" > test/test.md

    - name: Pull Request folder
      uses: fernandodpcarvalho/pull-request-another-repo@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'test'
        destination_repo: 'fernandodpcarvalho/teste'
        destination_folder: 'teste'
        destination_branch: 'pull-request-folder'
        user_email: 'fernandodpcarvalho@gmail.com'
        user_name: 'fernandodpcarvalho'
